<?php
$post_title = "Pondok Pesantren El-Bayan Majenang";
$post_image = "assets/banner/pp.webp";
$post_content ="
<p>Yayasan El-Bayan Majenang adalah sebuah pondok pesantren yang memiliki sejarah panjang dan kaya di Majenang, Kabupaten Cilacap, Jawa Tengah. Berdiri lebih dari 70 tahun yang lalu, pondok pesantren ini menerapkan metode pembelajaran salaf dengan menggunakan kitab kuning sebagai acuan². Selain itu, Yayasan El-Bayan juga mendukung pendidikan formal untuk membekali santri dengan ilmu pengetahuan umum, sehingga mereka tidak tertinggal dengan perkembangan zaman.</p>
<center><img src='assets/image/pp1.webp' alt='$post_title' height='320px' width='auto'></center><br>
<p>Pondok Pesantren El-Bayan didirikan oleh Kiahi M. Syuhud pada tahun 1930 dan awalnya dikenal sebagai Pondok Pesantren Bendasari Majenang (PPBM). Setelah beliau wafat pada tahun 1954, pengelolaan pondok pesantren dilanjutkan oleh putranya, K.H. Najmudin, yang merupakan alumni pesantren Tebuireng, Jombang. Dalam perkembangannya, pondok pesantren ini terus beradaptasi dengan laju globalisasi dan informasi, menggabungkan sistem pendidikan non-formal dan formal, dan akhirnya dikenal dengan nama Yayasan PP. El-Bayan.</p>
<center><img src='assets/image/pp2.webp' alt='$post_title' height='320px' width='auto'></center><br>
<p>Visi dari pendidikan di Pondok Pesantren El-Bayan adalah untuk membentuk manusia yang bertaqwa dan berakhlaqul karimah, dengan misi membantu masyarakat dalam mewujudkan generasi Islam yang berhaluan ahlisunnah wal jamaah yang terampil dan mandiri. Selain itu, pondok pesantren ini memiliki fasilitas yang mencakup masjid, asrama pesantren, gedung sekolah, dan berbagai ekstrakurikuler seperti Tahfidzul Al-Qur'an, Pengajian Kitab Kuning, Seni Hadrah/Marawis, Paduan Suara, Seni Musik, dan lainnya.</p>
<center><img src='assets/image/pp3.webp' alt='$post_title' height='320px' width='auto'></center><br>
<p>Pondok Pesantren El-Bayan berdiri diawali dari rasa tanggung jawab terhadap kewajiban menyiarkan agama Islam di seluruh pelosok tanah air. Atas dasar tersebut, KM. Syuhud pada tahun 1930 mendirikan Masjid yang mempunyai fungsi ganda atau double role yakni untuk menjalankan ibadah mahdloh dan digunakan untuk tempat mencari ilmu/mengaji. Kegiatan tersebut mendapat respon positif dari masyarakat sekitar dan dalam perkembangannya berdirilah Pondok Pesantren Bendasari Majenang (PPBM). Setelah beliau wafat tahun 1954, pengelolaan pondok pesantren dilanjutkan oleh putranya yaitu KH. Najmudin yang merupakan alumni pesantren Tebuireng, Jombang. </p>
<center><img src='assets/image/pp4.webp' alt='$post_title' height='320px' width='auto'></center><br>
<p>Seiring dengan laju globalisasi yang demikian pesat yang ditandai dengan derasnya laju informasi dan estafeta pimpinan, pengasuh pondok pesantren merasa perlu untuk lebih mengembangkan kembali kombinasi sistem pendidikan non formal dan formal, maka kemudian dibuat norma untuk mengatur seluruh kegiatan baik meliputi proses belajar mengajar, pengasuh yang kemudian menjadi dewan pengasuh, mengklasifikasikan santri dan peserta didik, hubungan antar masing-maing lembaga yang ada dan masih banyak lainnya yang kemudian diberi nama Norma Yayasan PP. El-Bayan. Estafeta kepemimpinan pondok pada tahun 2002 dari KH. Najmudin (wafat Februari 2002) dilanjutkan oleh kedua putranya, yaitu, KH. Imam Subky Najmudin alumni pondok Tebuireng yang notabene pencetus perubahan nama menjadi PP El-Bayan pada tahun 1971 dan KH. Mahsun Yusuf Najmudin alumni pondok Ploso Kediri.</p>

<p>Dalam penyelenggaraan pendidikan, PP El-Bayan mempunyai visi membentuk manusia yang bertaqwa dan berakhlaqul karimah. </p>

";
include 'posts/post_template.php'; ?>